---
apiVersion: v1
kind: Service
metadata:
  name: helloworldapp
  labels:
    app: helloworldapp
spec:
  type: NodePort
  selector:
    app: helloworldapp
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapp
spec:
  selector:
    matchLabels:
      app: helloworldapp
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworldapp
    spec:
      containers:
      - name: helloworldapp
        image: amiyakumar/helloworldapp:latest
        ports:
        - containerPort: 8020
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
